### ISSUE TITLE
Can't connect to AR1100

### ISSUE THREAD

**Issue by tehniemer** [tom-2015/rpi-AR1100#2]
I'm getting an error message saying 

````
Could not connect to the AR1100!
````

It is connected and I can calibrate it with xinput-calibrator, not sure why I'm seeing this message. I have this version https://www.adafruit.com/product/1580 and I'm on Raspbian 9

**Comment by tom-2015** [comment]
It's possible they changed something in Debian 9 that it incompatible...
But I don't have an AR1100 + touch screen here right now so I can't test it this weekend.
If you have a second SD card you could try with an older Raspbian 7 or 8, calibrate and then insert the Raspbian 9 card.
You can also calibrate in Windows if you can connect the touch screen to a computer.

**Comment by tehniemer** [comment]
I'll give Jessie a try, I can't use a windows PC because the screen is RCA only and I don't have anything but the pi that has RCA out...

**Comment by tehniemer** [comment]
Installing on Jessie did the trick.
