### ISSUE TITLE
Compiling on Ubuntu 18.04

### ISSUE THREAD

**Issue by seth-teamfdi** [tom-2015/rpi-AR1100#5]
By default, your code will not compile on a desktop distribution of Ubuntu 18.04 LTS. However, I have found the solution and it may be helpful to others to make this change so that it can be run on desktops as well as the RPi. All you have to do is change the makefile. The issue is that Ubuntu requires that the libraries that are required come at the end of the final build command. I.E. change the line $(CXX) $(CXXFLAGS) $(LINK) $(OBJS) -o $(APPNAME) to this instead $(CXX) $(CXXFLAGS) $(OBJS) -o $(APPNAME) $(LINK). I have tested this change on a RPi 3B+ and it still compiles and runs fine on the Pi as well as desktop Ubuntu 18.04. Of course feel free to test the change for yourself on a Pi to validate that there is no issues on the Pi side first. Thanks!

**Comment by tom-2015** [comment]
Ok Changed it
